#!/usr/bin/env python3
"""Generate the identity-keyed avatar tints in `ui/theme/AvatarTint.kt`.

Run it, then paste the printed block over the generated lists in
`app/src/main/java/app/getknit/knit/ui/theme/AvatarTint.kt`:

    python3 scripts/gen-avatar-palette.py

**What it makes.** A photo-less avatar is a coloured disc with an initial, and the disc's hue is keyed on
the identity it stands for (`avatarTintIndex`), so a list of strangers is not a column of identical
`secondaryContainer` circles and the same person wears the same colour on every phone. This prints the
palette those hues come from: HUES hues, evenly spaced around the HCT wheel, each as a light and a dark
`AvatarTint` (the disc's `container` plus the initial's `onContainer`) at Material's container tones.

**Why the chroma is capped, not requested.** HCT gamut-maps by lowering chroma at fixed hue and tone, and
the sRGB gamut is far from round: at tone 85 a coral (hue 30) can carry chroma ~21 while a green (hue 150)
can carry ~86. Ask every hue for the same generous chroma and the greens shout while the corals whisper.
So each mode's chroma is the most that *every* hue in the set can reach at its tone (`LIGHT`/`DARK` below
sit just under that floor, measured by `max_chroma()`), which is what makes the twelve discs read as one
set with no loud member. The letters use the same hue at Material's on-container tones (10 light, 90
dark) — the pairing every `*Container`/`on*Container` role in `Color.kt` already uses.

Depends on the HCT port in `gen-color-scheme.py` (imported by path, since the file name is not a module
name); its `self_test()` is run first so a broken port fails here rather than in the pasted colours.
"""

import importlib.util
import os
import sys

# --- The palette -------------------------------------------------------------

# Hue count. Twelve keeps neighbours ~30 degrees apart, the point at which two pastel discs side by side
# still read as different colours; more buckets would cost that without buying much identity.
HUES = 12

# (tone, chroma) of the disc and tone of the initial, per mode. Chroma must not exceed the smallest
# max_chroma() over the hue set at that tone — check() enforces it.
LIGHT = {"tone": 85.0, "chroma": 20.0, "on_tone": 10.0}
DARK = {"tone": 30.0, "chroma": 28.0, "on_tone": 90.0}


def _load_hct():
    here = os.path.dirname(os.path.abspath(__file__))
    spec = importlib.util.spec_from_file_location("gen_color_scheme", os.path.join(here, "gen-color-scheme.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def hues():
    return [i * 360.0 / HUES for i in range(HUES)]


def max_chroma(hct, hue, tone):
    """The largest chroma sRGB can display at (hue, tone): what asking for an impossible 120 gamut-maps to."""
    return hct.cam16_from_argb(hct.hct_to_argb(hue, 120.0, tone))[1]


def check(hct, mode, name):
    floor = min(max_chroma(hct, hue, mode["tone"]) for hue in hues())
    print(f"# {name}: tone {mode['tone']:.0f} admits chroma {floor:.1f} at the weakest hue; using {mode['chroma']:.1f}")
    if mode["chroma"] > floor:
        print(f"ERROR: {name} chroma {mode['chroma']:.1f} exceeds what every hue can reach ({floor:.1f}); lower it.", file=sys.stderr)
        return False
    return True


def emit(hct, mode, name):
    print(f"internal val {name} =")
    print("    listOf(")
    for hue in hues():
        disc = hct.hex_of(hct.hct_to_argb(hue, mode["chroma"], mode["tone"]))
        letter = hct.hex_of(hct.hct_to_argb(hue, mode["chroma"], mode["on_tone"]))
        print(f"        AvatarTint(container = Color(0xFF{disc}), onContainer = Color(0xFF{letter})), // hue {round(hue)}")
    print("    )")


def main():
    hct = _load_hct()
    hct.self_test()
    if not (check(hct, LIGHT, "light") and check(hct, DARK, "dark")):
        return 1
    print()
    print(f"// Generated by scripts/gen-avatar-palette.py -- {HUES} hues {360.0 / HUES:.0f} degrees apart in HCT.")
    print(f"// Light: disc tone {LIGHT['tone']:.0f} / chroma {LIGHT['chroma']:.0f}, initial tone {LIGHT['on_tone']:.0f}. "
          f"Dark: disc tone {DARK['tone']:.0f} / chroma {DARK['chroma']:.0f}, initial tone {DARK['on_tone']:.0f}.")
    emit(hct, LIGHT, "AvatarTintsLight")
    print()
    emit(hct, DARK, "AvatarTintsDark")
    return 0


if __name__ == "__main__":
    sys.exit(main())
